# Generated by Django 2.1.5 on 2019-02-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first',
            field=models.CharField(default='First', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last',
            field=models.CharField(default='Last', max_length=100),
        ),
    ]
