# Generated by Django 2.1.7 on 2019-03-05 22:22

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190305_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
        migrations.AddField(
            model_name='profile',
            name='allergies',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.TaggedAllergies', to='users.AllergyTags', verbose_name='Tags'),
        ),
    ]
