# Generated by Django 2.1.7 on 2019-03-05 22:22

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0004_auto_20190305_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestrictionTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('sensetivity', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name': 'Restriction Tag',
                'verbose_name_plural': 'Restriction Tags',
            },
        ),
        migrations.CreateModel(
            name='TaggedRestrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='Object id')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_taggedrestrictions_tagged_items', to='contenttypes.ContentType', verbose_name='Content type')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_TaggedRestrictions_items', to='users.RestrictionTags')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='taggedallergies',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taggedallergies',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='allergies',
        ),
        migrations.DeleteModel(
            name='AllergyTags',
        ),
        migrations.DeleteModel(
            name='TaggedAllergies',
        ),
        migrations.AddField(
            model_name='profile',
            name='restrictions',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='users.TaggedRestrictions', to='users.RestrictionTags', verbose_name='Tags'),
        ),
    ]
