# Generated by Django 2.1.5 on 2019-02-04 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='event_ptr',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='guest',
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='RSVP_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
