# Generated by Django 2.1.5 on 2019-02-18 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20190218_0705'),
        ('events', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='event',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='food',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='guest',
        ),
        migrations.AddField(
            model_name='invitation',
            name='food',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Food'),
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
