# Generated by Django 2.1.5 on 2019-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190218_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='attending',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='replied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
