# Generated by Django 2.1.7 on 2019-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190218_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(blank=True, help_text='Please use the format <em>HH:MM (AM/PM)</em>.', null=True),
        ),
    ]
