# Generated by Django 2.1.5 on 2019-02-18 04:37

from django.db import migrations, models
import menus.models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20190218_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='number_of_servings',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
