# Generated by Django 2.1.5 on 2019-02-18 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20190218_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='number_of_servings',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
