# Generated by Django 2.1.5 on 2019-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0006_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='food',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='guest',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='menu',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
