# Generated by Django 2.1.7 on 2019-02-27 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0007_auto_20190218_0705'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TagMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Menu')),
                ('tags', models.ManyToManyField(to='menus.FoodTag')),
            ],
            bases=('menus.menu',),
        ),
        migrations.AddField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(to='menus.FoodTag'),
        ),
    ]
