# Generated by Django 2.1.7 on 2019-02-27 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0008_auto_20190227_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=models.ManyToManyField(blank=True, to='menus.FoodTag'),
        ),
    ]
