# Generated by Django 2.1.7 on 2019-03-02 07:37

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190302_0645'),
        ('taggit', '0002_auto_20150616_2121'),
        ('menus', '0008_auto_20190227_1940'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodTag',
        ),
        migrations.DeleteModel(
            name='TagMenu',
        ),
        migrations.RemoveField(
            model_name='food',
            name='tags',
        ),
        migrations.AddField(
            model_name='food',
            name='food_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
