# Generated by Django 2.1.7 on 2019-03-04 17:02

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0010_auto_20190304_0206'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProportionMenu',
            fields=[
                ('menu_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menus.Menu')),
                ('proportions', models.ManyToManyField(to='menus.Proportion')),
            ],
            bases=('menus.menu',),
        ),
        migrations.AlterField(
            model_name='food',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
