# Generated by Django 2.1.7 on 2019-03-06 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190302_0645'),
        ('menus', '0012_auto_20190305_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProportionMenu',
        ),
        migrations.AddField(
            model_name='proportion',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menus.Menu'),
        ),
    ]
